print("Hello I am Tejal Here")
print("Hello this line also added...")
print("Hello we will do later work tomorrow at Early Morning")
print("Ok Mam..Done.!")
print("Hello..Started work at Early Morning..!")
print()